[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true
address = "0.0.0.0"
baseUrlPath = ""
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0066cc"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
